apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lalaland

spec:
  description: This is LalaLand
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
