apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.3.1
  - apps/argocd-server.yaml
  - projects/project-lalaland.yaml

patchesStrategicMerge:
  - overlays/hotel-budapest/argocd-rbac-cm.yaml
