apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/part-of: argocd

data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow

    g, your-github-org:your-team, role:org-admin
    g, lala:team2, role:org-admin
    g, catenax-ng:ArgoCDAdmins, role:admin
